config/routes.rb
Rails.application.routes.draw do
  root 'categories#index'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks"}

  resources :categories, :posts

  resources :users do
    collection do
      get 'choose_categories'
      post 'choose_categories'
    end
  end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :post_categories
  has_many :posts, through: :post_categories
end

app/models/category_user.rb
class CategoryUser < ApplicationRecord
  belongs_to :category
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :post_categories
  has_many :categories, through: :post_categories

  def self.search(search)
    where('title ILIKE ? OR plain_text ILIKE ?', "%#{search}%", "%#{search}%")
  end
end

app/models/post_category.rb
class PostCategory < ApplicationRecord
  belongs_to :category
  belongs_to :post
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  has_many :category_users, dependent: :destroy
  has_many :categories, through: :category_users

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  devise :omniauthable, omniauth_providers: %i[facebook]

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.name = auth.info.name   # assuming the user model has a name
      user.image = auth.info.image # assuming the user model has an image
      # If you are using confirmable and the provider(s) you use validate emails,
      # uncomment the line below to skip the confirmation emails.
      # user.skip_confirmation!
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def after_sign_in_path_for(resource)
    if current_user.categories.count > 0
      root_path
    else
       choose_categories_users_path
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[show edit update destroy]

  def index
    @categories = Category.all.order('title asc')
  end

  def show; end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to root_path, notice: "Category #{@category.title} has been created"
    else
      render :new
    end
  end

  def edit; end

  def update
    if @category.update(category_params)
      redirect_to @category, notice: "Category #{@category.title} has been edited"
    else
      render :edit
    end
  end

  def destroy
    @category.destroy
    redirect_to root_path
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:title)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  require 'open-uri'
  before_action :set_post, only: [ :show, :edit, :update, :destroy]

  def index
    @posts = if params[:search]
           Post.search(params[:search]).order('created_at DESC')
         else
           Post.all.order('title asc')
         end
  end

  def show
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    row_post = Nokogiri::HTML(open(params.dig(:post, :url)).read)
    @post.title = row_post.title
    if params.dig(:post, :url).include?("habr")
      @post.body = row_post.at_css('[id="post-content-body"]').text
    elsif params.dig(:post, :url).include?("tsn")
      @post.body = row_post.at_css('[class="e-content"]')
    elsif params.dig(:post, :url).include?("telegra")
      @post.body = row_post.at_css('[id="_tl_editor"]')
    end
    @post.user_id = current_user.id
    if @post.save
      redirect_to @post, success: "Новая статья успешно создана"
    else
      render :new, danger: "Статья не создана"
    end
  end

  def edit
  end

  def update
    if @post.update_attributes(post_params)
      redirect_to @post, success: "Статья успешно обновленна"
    else
      render :edit, danger: "Статья не обновлена"
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path, warning: "Статья удаленна"
  end

  private
  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:url, category_ids: [])
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  after_action :redirect, only: %w[choose_categories]

  def choose_categories
    @categories = Category.all
    current_user.categories = Category.where(id: params[:category_ids])
  end

  def update
    if current_user.update_attributes(user_params)
      redirect_to root_path, success: "Updated!"
    end
  end

  def show
    @user = User.find_by_id(params[:id])
    @posts = Post.where(user_id: @user.id)
  end

  def redirect
    redirect_to root_path if current_user.categories.count > 0
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/custom_session_helper.rb
module CustomSessionHelper
end

app/helpers/custom_sessions_helper.rb
module CustomSessionsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/_form.html.erb
<div class="container">
  <%= form_with(model: @category, local: true) do |form| %>
    <% if @category.errors.any? %>
      <div class="alert alert-danger">
        <ul>
          <% @category.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field mt-5">
      <%= form.label :title %>
      <%= form.text_field :title, class: "form-control"%>
    </div>

    <div class="ml-auto mt-2">
      <%= form.submit 'Submit', class: "btn btn-outline-dark" %>
    </div>
  <% end %>
</div>

app/views/categories/index.html.erb
<div class="container">
  <% @categories.each do |category| %>
    <p class="category-index"><%= link_to category.title, category_path(category) %></p>
  <% end %>
</div>

app/views/categories/new.html.erb
<h1 class="container">New category</h1>
<%= render 'form' %>

app/views/categories/show.html.erb
<div class="container">
  <% @category.posts.each do |post| %>
    <p><%= link_to post.title, post_path(post), class: 'category-show' %></p>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dashboard</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<% if @post.errors.any? %>
  <div class="alert alert-danger">
    <h5><%= t('common.errors') %></h5>
    <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%=message%> </li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @post, html: {multipart: true} do |f| %>
  <div class="form-group">
    <%= f.label :url %>
    <%= f.text_field :url, class: 'form-control' %>
  </div>

  <div class="field mt-5">
    <%= f.label :category %>
    <%= f.collection_check_boxes :category_ids, Category.all, :id, :title, class:'form-control' %>
  </div>


  <div class="form-group">
    <%= f.submit "Submit", class: 'btn btn-primary' %>
    <%= link_to t('common.back'), :back, class: 'btn btn-outline-secondary' %>
  </div>

<% end %>

app/views/posts/new.html.erb
<div class="container">
  <h1>New post</h1>
  <%= render 'form' %>
</div>

app/views/posts/show.html.erb
<article class="post container">
  <section class="post-head">
    <h1><%= @post.title %></h1>
    <small>
      <time><%= @post.created_at.to_date.strftime("%d %B, %Y") %></time>
      <% if @post.user_id = current_user.id %>
        |
        <%= link_to 'Изменить', edit_post_path(@post) %>
        |
        <%= link_to 'Удалить', post_path(@post), method: :delete, data: { confirm: 'Вы уверены?' } %>
      <% end %>

    </small>
  </section>

  <section class="post-body container">
    <%= raw @post.body %>
  </section>
</article>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to "DashBoard", root_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if current_user %>
        <li class="nav-item active">
          <%= link_to current_user&.email, user_path(current_user), class: "nav-link" %>
        </li>
        <li class="nav-item active">
          <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "nav-link" %>
        </li>
      <% else %>
        <%= link_to "Sign in with Facebook", user_facebook_omniauth_authorize_path %>
      <% end %>
      <li class="nav-item">
        <%= link_to "Create Post", new_post_path, class: "nav-link btn btn-outline-dark" if current_user %>
      </li>
      <li class="nav-item">
        <%= link_to "Create Category", new_category_path, class: "nav-link" if current_user&.admin? if current_user %>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <%= text_field_tag :search, params[:search], placeholder: "Search Posts", class: "form-control" %>
      <%= submit_tag "Search", class: "btn btn-outline-primary" %>
    </form>
  </div>
</nav>

app/views/users/choose_categories.html.erb
<%= form_with(model: @user, local: true) do |f| %>
  <div class="field mt-5">
    <%= f.label :category %>
    <%= f.collection_check_boxes :category_ids, Category.all, :id, :title, class:'form-control' %>
  </div>

  <div class="form-group">
    <%= f.submit "Submit", class: 'btn btn-primary' %>
    <%= link_to t('common.back'), :back, class: 'btn btn-outline-secondary' %>
  </div>
<% end %>

app/views/users/index.html.erb
<div class="container">
  <h1>test</h1>
  <h1><%= @test %></h1>
</div>

app/views/users/show.html.erb
<div class="container">
  <% if @user.id = current_user.id %>
    <h2>My posts:</h2>
    <% @posts.each do |post| %>
      <%= link_to post.title, post_path(post), class: "posts-user" %>
    <% end %>
  <% else %>
    <h2>User posts:</h2>
    <% @posts.each do |post| %>
      <%= link_to post.title, post_path(post), class: "posts-user" %>
    <% end %>
  <% end %>
</div>